export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const CONTACT_COMPLETE = "CONTACT_COMPLETE";
export const GET_BLOG_DATA = "GET_BLOG_DATA";
export const DELETE_BLOG_DATA = "DELETE_BLOG_DATA";
export const GET_CONTACT_DATA = "GET_CONTACT_DATA";
export const GET_BANNER_DATA = "GET_BANNER_DATA";
export const DELETE_BANNER_DATA = "DELETE_BANNER_DATA";
export const OPEN_NAV = "OPEN_NAV";
export const CLOSE_NAV = "CLOSE_NAV";
export const GET_SERVICE_DATA = "GET_SERVICE_DATA";
export const DELETE_SERVICE_DATA = "DELETE_SERVICE_DATA";
export const GET_PROJECT_DATA = "GET_PROJECT_DATA";
export const DELETE_PROJECT_DATA = "DELETE_PROJECT_DATA";

export const GET_TEAM_DATA = "GET_TEAM_DATA";
export const DELETE_TEAM_DATA = "DELETE_TEAM_DATA";
export const DELETE_VIDEO_DATA = "DELETE_VIDEO_DATA";

